language: python
python:
  - "3.3"
  - "2.7"
install:
  - pip install coveralls --use-mirrors
script:
    - coverage run --source=euler setup.py test
    - coverage report -m
after_success:
    - coveralls
